# Generated by Django 4.1 on 2026-02-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_student_about_alter_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
    ]
