# Generated by Django 4.1 on 2026-02-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='password',
            field=models.IntegerField(max_length=10),
        ),
    ]
